### ISSUE TITLE
hey，番茄的朋友；想问问你这个交易记录是每天手动/自动更新的？然后是通过监听邮箱更新的吗？

### ISSUE THREAD

**Issue by sooxt98** [KarlZhu-SE/ark-funds-monitor#190]

**Comment by KarlZhu-SE** [comment]
你好，数据来自每日邮件，现在是手动更新的。
因为ARK有时会有错误邮件，又重发corrected version，导致本来写好的script容易出错。

**Comment by sooxt98** [comment]
@KarlZhu-SE 哦哦，那个那么有机会自动化吗？我怕哪天你太忙了，就停止了更新

**Comment by KarlZhu-SE** [comment]
这个小项目只是个人兴趣，也不认识番茄。
script这个不是太容易，第一是ark会在同一天重复发相同邮件，第二是有时候第一封邮件数据或者排版错误又发第二封。
我只能尽量搜集邮件，哪怕有一两天太忙，之后也能补上。

**Comment by sooxt98** [comment]
你不认识番茄？！这么说资料都是邮箱来的？而不是从ark etf的pdf中逆向反推出来的？

**Comment by KarlZhu-SE** [comment]
应该是他拿了一部分我开源的代码吧。

Best,
Karl Zhu

**Comment by sooxt98** [comment]
@KarlZhu-SE 原来如此，那接下来的问题呢？每天的交易操作是从ark etf的pdf中逆向反推出来的么？

**Comment by KarlZhu-SE** [comment]
我的项目只是用的交易邮件。他的我不太清楚。 Sincerely,Karl Zhu From: sooxt98Sent: Sunday, March 21, 2021 21:42To: KarlZhu-SE/ark-funds-monitorCc: Karl Zhu; MentionSubject: Re: [KarlZhu-SE/ark-funds-monitor] hey，番茄的朋友；想问问你这个交易记录是每天手动/自动更新的？然后是通过监听邮箱更新的吗？ (#190) @KarlZhu-SE 原来如此，那接下来的问题呢？每天的交易操作是从ark etf的pdf中逆向反推出来的么？—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
